version: '2'

services:
  postgres:
    image: postgres:latest
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  rhythm:
    build: .
    volumes:
          - .:/var/www/html
    depends_on:
      - postgres
    command: /usr/sbin/apache2ctl -D FOREGROUND
    ports:
      - "80:80"
