postgres:
  image: postgres:latest
  volumes:
    - ./postgres:/docker-entrypoint-initdb.d/
  ports:
    - 5432:5432

rhythm:
  dockerfile: Dockerfile
  build: .
  volumes:
        - .:/var/www/html
  links:
    - postgres:pg
  ports:
    - 80:80
